"""add_proposals_table

Revision ID: 5de29207edd8
Revises: 28a189a814bd
Create Date: 2026-06-24 21:58:23.096780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5de29207edd8'
down_revision: Union[str, Sequence[str], None] = '28a189a814bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposal_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('scope_understanding', sa.Text(), nullable=False),
    sa.Column('compliance_section', sa.Text(), nullable=False),
    sa.Column('required_deliverables', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_drafts_document_id'), 'proposal_drafts', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_drafts_document_id'), table_name='proposal_drafts')
    op.drop_table('proposal_drafts')
    # ### end Alembic commands ###

